#ifndef _MAPSERVER_VERSION_H
#define _MAPSERVER_VERSION_H

#define MS_VERSION_MAJOR 8
#define MS_VERSION_MINOR 1
#define MS_VERSION_REV 0
#define MS_VERSION "8.1-dev"
#define MS_VERSION_NUM  80100 

#endif

